### ISSUE TITLE
move to ghe

### ISSUE THREAD

**Issue by enriclluelles** [scm-spain/cluster_deployer#1]
I created https://github.schibsted.io/scmspain/dvo-deployer, we should remove this one and focus on the other

**Comment by danielricart** [comment]
If this repository is migrated to GHE it should be emptied and linked to the working one.

**Comment by ferrangrau** [comment]
No, it not moved to GHE because is an open source repository with public access, this is the correct repo now. The PR was a mistake, so that is closed.
